# -*- coding: utf-8 -*-
"""Копия блокнота "Практика BeautifulSoup.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ylgLnbTH1lcDxMlWMTbiikCLrwIN4W0C

# Фильмы

1.   Новый пункт
2.   Новый пункт

Загружаем страницу и проверяем, что всё прошло хорошо
"""

pip install beautifulsoup4

pip install requests

from bs4 import BeautifulSoup
import requests

url = 'https://www.kinopoisk.ru/lists/top250/anime/?tab=all'
response = requests.get(url)
print(response.status_code)

"""Готовим суп"""

soup = BeautifulSoup(response.text, 'lxml')

"""Выгружаем цитаты"""

films = soup.find_all('p', class_='selection-film-item-meta__name')

for film in films:
    print(film.text)

"""Добавляем ко всему прочему авторов"""

authors = soup.find_all('p', class_='selection-film-item-meta__original-name')
aut = []
aut2=[]
aut3=[]
country = soup.find_all('span', class_='selection-film-item-meta__meta-additional-item') 
imagess = soup.find_all('img', class_='selection-film-item-poster__image' )
for m in range(0, len(authors)):
  aut.append(authors[m].text)
for k in range(0, len(aut)):
   aut2.append(aut[k].split(', '))
for i in range(0, len(films)):
    aut3.append('Название: '+films[i].text+'\n'+'Оригинальное название: '+aut2[i][0]+'\n'+'Год: '+aut2[i][1]+'\n'+'Страна: '+country[::2][i].text+'\n'+'Жанр: '+country[1::2][i].text+'\n')

for t in range(0, len(aut3)):
  print("".join(aut3[t]))

authors = soup.find_all('p', class_='selection-film-item-meta__original-name')
aut = []
for m in range(0, len(authors)):
  print(authors[m].text)

aut2

authors

"""И вишенкой на торте будут теги"""

tags = soup.find_all('div', class_='tags')

for i in range(0, len(quotes)):
    print(quotes[i].text)
    print('--' + authors[i].text)
    tagsforquote = tags[i].find_all('a', class_='tag')
    for tagforquote in tagsforquote:
        print(tagforquote.text)
    print('\n')

tags